version: "3"
services:
  postgres:
    image: postgres:15
    networks:
      - back
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: ezvuzdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bladerunner2049
    volumes:
      - postgres:/var/lib/postgresql/data
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=ezvuz.ru
      - LETSENCRYPT_HOST=ezvuz.ru
      - VIRTUAL_PORT=80
    networks:
      - back
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

volumes:
  postgres: